name: MLFlow-CI

on:
  push:
    branches: [ main ]

jobs:
  mlflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Conda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-update-conda: true
          activate-environment: mlflow  # beri nama environment

      # Inisialisasi Conda
      - name: Initialize Conda
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda info --envs
          
      # Install dependencies
      - name: Install dependencies
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate mlflow
          pip install mlflow

      # Jalankan MLFlow
      - name: Run MLFlow
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate mlflow
          mlflow run MLProject
