name: MLFlow-CI

on:
  push:
    branches: [ main ]

jobs:
  mlflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.9"
          auto-update-conda: true

      - name: Create Conda Environment
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda env create -f conda.yaml

      # Run MLflow Project
      - name: Run MLflow Project
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate mlflow-env
          mlflow run . -P data_path=FakeNewsNet_preprocessing.csv
