name: MLFlow-CI

on:
  push:
    branches: [ main ]

jobs:
  mlflow:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.9"
          auto-update-conda: true

      # Debug: list semua file untuk memastikan conda.yaml ada
      - name: List repo files
        run: ls -R

      # Run MLflow Project
      - name: Run MLflow Project
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          mlflow run MLProject -P data_path=FakeNewsNet_preprocessing.csv
