name: MLFlow-CI

on:
  push:
    branches: [ main ]

jobs:
  mlflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true

      # Create environment from conda.yaml
      - name: Create conda environment
        run: |
          conda env create -f MLProject/conda.yaml
          conda activate mlflow-env

      # Run Python script within conda env
      - name: Run Modelling Script
        run: |
          conda run -n mlflow-env python MLProject/modelling.py --data_path MLProject/FakeNewsNet_preprocessing.csv