name: MLFlow-CI

on:
  push:
    branches: [ main ]

jobs:
  mlflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Conda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ""
          auto-update-conda: true
          python-version: "3.10"

      # Inisialisasi conda ke shell (WAJIB!)
      - name: Initialize Conda
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda --version

      # Jalankan MLFlow project
      - name: Run MLFlow
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          mlflow run MLProject
name: MLFlow-CI

on:
  push:
    branches: [ main ]

jobs:
  mlflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Conda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ""
          auto-update-conda: true
          python-version: "3.10"

      # Inisialisasi conda ke shell (WAJIB!)
      - name: Initialize Conda
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda --version

      - name: Run MLFlow
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate base
          mlflow run .

